var a=10;
document.write("the value of a is:"+a+"<br>")
document.write("<br>")
document.write("the value of ++a is:"+ ++a +"<br>")
document.write("now the value of a is:"+a+"<br>")
document.write("<br>")
document.write("the value of a++ is:"+ a++ +"<br>")
document.write("now the value of a is:"+a+"<br>")
document.write("<br>")
document.write("the value of --a is:"+ --a +"<br>")
document.write("now the value of a is:"+a+"<br>")
document.write("<br>")
document.write("the value of a-- is:"+ a-- +"<br>")
document.write("now the value of a is:"+a+"<br>")
